import "./globals.css";
import { Inter } from "next/font/google";
import { Sidenavbar } from "@/components/sidebar/Sidebar";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vincent Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {}
      <head />
      <body>
        <Sidenavbar />
        <main className="sm:ml-64">{children}</main>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js" />
      </body>
    </html>
  );
}
